[package]
name = "joebot-markov-chain"
version = "0.1.0"
authors = ["texbois"]
edition = "2018"

[dependencies]
vkopt-message-parser = { git = "https://github.com/texbois/vkopt-message-parser" }
indexmap = "1.3"
chrono = "0.4"
rand = { version = "0.7", features = ["small_rng"] }
